# Dotfiles Configuration

# Master Switches
enable_preferences: false # Disabled by default for safety
enable_tools: true # Most users want tools
enable_aliases: true # Shell aliases are safe
enable_vim: true # Editor config is safe
enable_file_assoc: true # File associations are safe
enable_snapshots: true # Create APFS snapshot before changes

# User Information
user:
  name: 'Shane Holloman'
  email: 'shaneholloman@gmail.com'

# Paths and Locations
paths:
  dotfiles: '$HOME/.dotfiles'
  oh_my_posh_theme: '$HOME/Dropbox/shane/conf/warpdeck.omp.json'

# Git Configuration
git:
  editor: 'vim'
  default_branch: 'main'
  pull_rebase: true
  color_ui: true

# Shell Configuration
shell:
  default: 'zsh'
  theme:
    type: 'oh-my-posh'
    path: '~/Dropbox/shane/conf/warpdeck.omp.json'
  env_vars:
    AWS_CONFIG_FILE: '$HOME/.aws/config'
    AWS_SHARED_CREDENTIALS_FILE: '$HOME/.aws/credentials'
    KUBECONFIG: '$HOME/.kube/config'
    TERRAFORM_CONFIG: '$HOME/.terraform.d/config.tfrc'

# Tools to Install
tools:
  cli:
    - ack
    - awscli
    - bash
    - bash-completion2
    - cmake
    - findutils
    - gh
    - gmp
    - gnu-sed
    - gnupg
    - go
    - grep
    - helm
    - imagemagick
    - jq
    - kubernetes-cli
    - lua
    - lynx
    - moreutils
    - oh-my-posh
    - openssh
    - p7zip
    - php
    - pigz
    - pkgconf
    - pv
    - rename
    - rlwrap
    - rust
    - screen
    - terraform
    - tree
    - uv
    - volta
    - yq

  cask:
    - docker
    - claude
    - ollama
    - iterm2
    - dropbox
    - firefox
    - spotify
    - font-hack-nerd-font # used for terminal and vscode
    - powershell # yet to add oh-my-posh as we already have for zsh
    - visual-studio-code # intent is to add plugins/setting via another module
    - visual-studio-code@insiders # intent is to add plugins/setting via another module

  forensic:
    # - aircrack-ng
    # - bfg
    # - binutils
    # - binwalk
    # - cifer
    # - dex2jar
    # - dns2tcp
    # - fcrackzip
    # - foremost
    # - hashpump
    # - hydra
    # - john
    # - knock
    # - netpbm
    # - nmap
    # - pngcheck
    # - socat
    # - sqlmap
    # - tcpflow
    # - tcpreplay
    # - tcptrace
    # - ucspi-tcp
    # - xpdf
    # - xz

# Aliases
aliases:
  d: 'docker'
  dc: 'docker-compose'
  g: 'git'
  gcb: 'git checkout -b'
  gco: 'git checkout'
  gp: 'git pull'
  gs: 'git status'
  k: 'kubectl'
  ll: 'ls -la'
  tf: 'terraform'

# Directory Structure
directories:
  - bin
  - config/git
  - config/zsh
  - config/vim
  - config/aws
  - config/terraform
  - config/k8s
  - scripts

# User Preferences
preferences:
  terminal:
    font: 'Hack Nerd Font Mono 12'
    key_repeat: 1
    initial_key_repeat: 10
    press_and_hold: false

# Vim Configuration
vim:
  options:
    - 'syntax on'
    - 'set number'
    - 'set ruler'
    - 'set expandtab'
    - 'set tabstop=2'
    - 'set shiftwidth=2'
    - 'set autoindent'
    - 'set smartindent'
    - 'set paste'
    - 'set hlsearch'
    - 'set incsearch'
    - 'set cursorline'
  filetypes:
    yaml: 'setlocal ts=2 sts=2 sw=2 expandtab'
    terraform: 'setlocal ts=2 sts=2 sw=2 expandtab'
    json: 'setlocal ts=2 sts=2 sw=2 expandtab'

# File Associations Configuration
file_associations:
  editor:
    bundle_id: 'com.microsoft.VSCodeInsiders'
  extensions:
    - 'py' # Python
    - 'js' # JavaScript
    - 'ts' # TypeScript
    - 'css' # CSS
    - 'json' # JSON
    - 'md' # Markdown
    - 'xml' # XML
    - 'yaml' # YAML
    - 'yml' # YAML
    - 'sh' # Shell scripts

# Restore Configuration
restore:
  paths:
    mount_point: '/tmp/snap'
    disk_device: '/dev/disk3s5'
    user_home: '$HOME'
    root: '/'
    backup_dir_prefix: '.dotfiles_backup_'
  files:
    dotfiles:
      - '.zshrc'
      - '.bashrc'
      - '.gitconfig'
    config_dirs:
      - '.config'
      - '.aws'
      - '.terraform.d'
      - '.kube'
      - '.vscode-insiders'
