# Dotfiles Configuration

# Future, not implemented yet.

# Master Switches
enable_preferences: false      # System preferences and defaults
enable_tools: true             # CLI and GUI tools installation
enable_aliases: true           # Shell aliases and functions
enable_vim: true               # Vim configuration
enable_file_assoc: true        # File associations
enable_security: false         # Security configurations
enable_dev_env: true           # Development environment setup
enable_app_config: true        # Application specific configurations
enable_system_defaults: false  # macOS system defaults
enable_backup: true            # Backup functionality

# System Configuration
system:
  hostname: 'macbook-pro'
  computer_name: 'Shane's MacBook Pro'
  timezone: 'Pacific/Auckland'
  locale:
    lang: 'en_US.UTF-8'
    lc_all: 'en_US.UTF-8'

# User Information
user:
  name: 'Shane Holloman'
  email: 'shaneholloman@gmail.com'
  github_username: 'shaneholloman'

# Security Configuration
security:
  ssh:
    key_type: 'ed25519'
    key_bits: 4096
    generate_keys: true
  gpg:
    generate_key: true
    default_key: ''
  firewall:
    enable: true
    stealth_mode: true
  filevault:
    enable: true

# Paths and Locations
paths:
  dotfiles: '$HOME/.dotfiles'
  oh_my_posh_theme: '$HOME/Dropbox/shane/conf/warpdeck.omp.json'
  backup_dir: '$HOME/.dotfiles_backup'
  local_bin: '$HOME/.local/bin'

# Git Configuration
git:
  editor: 'vim'
  default_branch: 'main'
  pull_rebase: true
  color_ui: true
  commit:
    gpgsign: true
  init:
    defaultBranch: 'main'

# Shell Configuration
shell:
  default: 'zsh'
  theme:
    type: 'oh-my-posh'
    path: '~/Dropbox/shane/conf/warpdeck.omp.json'
  history:
    size: 50000
    format: '%F %T '
    ignorespace: true
  completion:
    case_sensitive: false
    hyphen_insensitive: true
  env_vars:
    AWS_CONFIG_FILE: '$HOME/.aws/config'
    AWS_SHARED_CREDENTIALS_FILE: '$HOME/.aws/credentials'
    KUBECONFIG: '$HOME/.kube/config'
    TERRAFORM_CONFIG: '$HOME/.terraform.d/config.tfrc'
    GOPATH: '$HOME/go'
    CARGO_HOME: '$HOME/.cargo'
    NVM_DIR: '$HOME/.nvm'
    PYENV_ROOT: '$HOME/.pyenv'

# Development Environment
dev_env:
  python:
    version: '3.11'
    packages:
      - 'pipenv'
      - 'poetry'
      - 'black'
      - 'pylint'
  node:
    version: '20'
    packages:
      - 'typescript'
      - 'eslint'
      - 'prettier'
  go:
    version: '1.21'
  rust:
    install: true
    components:
      - 'rustfmt'
      - 'clippy'

# Tools to Install
tools:
  cli:
    - bash # Modern bash via Homebrew
    - awscli
    - cmake
    - docker
    - gh
    - go
    - helm
    - jq
    - kubernetes-cli
    - oh-my-posh
    - terraform
    - volta
    - yq
    - ripgrep
    - fd
    - bat
    - exa
    - htop
    - tmux
    - neovim
  cask:
    - carbon-copy-cloner
    - claude
    - iterm2
    - dropbox
    - firefox
    - font-hack-nerd-font
    - powershell
    - visual-studio-code@insiders
    - docker
    - postman
    - rectangle
    - alfred

# Application Configurations
app_config:
  vscode:
    extensions_file: '$HOME/.dotfiles/config/vscode/extensions.txt'
    settings_file: '$HOME/.dotfiles/config/vscode/settings.json'
  iterm2:
    preferences_folder: '$HOME/.dotfiles/config/iterm2'
  terminal:
    theme: 'Solarized Dark'
    font: 'Hack Nerd Font Mono'
    font_size: 12

# Aliases
aliases:
  d: 'docker'
  dc: 'docker-compose'
  g: 'git'
  gcb: 'git checkout -b'
  gco: 'git checkout'
  gp: 'git pull'
  gs: 'git status'
  k: 'kubectl'
  ll: 'ls -la'
  tf: 'terraform'
  cat: 'bat'
  ls: 'exa'
  top: 'htop'

# Directory Structure
directories:
  - bin
  - config/git
  - config/zsh
  - config/vim
  - config/aws
  - config/terraform
  - config/k8s
  - config/vscode
  - config/iterm2
  - scripts
  - backups

# User Preferences
preferences:
  terminal:
    font: 'Hack Nerd Font Mono'
    font_size: 12
    key_repeat: 1
    initial_key_repeat: 10
    press_and_hold: false
  dock:
    autohide: true
    magnification: false
    position: 'bottom'
    minimize_effect: 'scale'
  finder:
    show_hidden_files: true
    show_path_bar: true
    show_status_bar: true
  input:
    keyboard:
      key_repeat: 2
      initial_key_repeat: 15
    trackpad:
      tap_to_click: true
      natural_scrolling: false

# Vim Configuration
vim:
  options:
    - 'syntax on'
    - 'set number'
    - 'set ruler'
    - 'set expandtab'
    - 'set tabstop=2'
    - 'set shiftwidth=2'
    - 'set autoindent'
    - 'set smartindent'
    - 'set paste'
    - 'set hlsearch'
    - 'set incsearch'
    - 'set cursorline'
  filetypes:
    yaml: 'setlocal ts=2 sts=2 sw=2 expandtab'
    terraform: 'setlocal ts=2 sts=2 sw=2 expandtab'
    json: 'setlocal ts=2 sts=2 sw=2 expandtab'

# File Associations Configuration
file_associations:
  editor:
    bundle_id: 'com.microsoft.VSCodeInsiders'
  extensions:
    - 'py'  # Python
    - 'js'  # JavaScript
    - 'ts'  # TypeScript
    - 'css' # CSS
    - 'json' # JSON
    - 'md'  # Markdown
    - 'xml' # XML
    - 'yaml' # YAML
    - 'yml' # YAML
    - 'sh'  # Shell scripts
    - 'tf'  # Terraform
    - 'go'  # Go
    - 'rs'  # Rust

# Backup Configuration
backup:
  enabled: true
  locations:
    - '$HOME/.ssh'
    - '$HOME/.gnupg'
    - '$HOME/.aws'
    - '$HOME/.kube'
    - '$HOME/.config'
  exclude:
    - '.DS_Store'
    - '*.log'
    - 'node_modules'
    - '.git'
  retention:
    days: 30
    copies: 5
