name: Capture Virgin macOS Configs

on:
  workflow_dispatch: # Manual trigger only

permissions:
  contents: write
  pull-requests: write

jobs:
  capture-configs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create virgin directory
        run: |
          mkdir -p config/zsh/virgin
          mkdir -p config/zsh/virgin/.config

      - name: Copy virgin configs
        run: |
          # Copy system zshrc
          sudo cp /private/etc/zshrc config/zsh/virgin/zshrc

          # Copy .config directory
          if [ -d ~/.config ]; then
            cp -R ~/.config/* config/zsh/virgin/.config/ || true
          fi

          # List captured files
          echo "Captured files:"
          ls -la config/zsh/virgin/
          echo "Captured .config contents:"
          ls -la config/zsh/virgin/.config/

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: capture virgin macOS configs"
          title: "chore: capture virgin macOS zshrc and .config"
          branch: capture-virgin-configs
          delete-branch: true
